name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# https://github.com/vitejs/vite/blob/main/.github/workflows/ci.yml
env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144


# Remove default permissions of GITHUB_TOKEN for security
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  local:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Connect and run command on remote server
        uses: and-fm/cloudflared-ssh-action@v3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          private_key_filename: ${{ secrets.SSH_PRIVATE_KEY_FILENAME }}
          private_key_value: ${{ secrets.SSH_PRIVATE_KEY_VALUE }}
          service_token_id: ${{ secrets.CLOUDFLARED_SERVICE_TOKEN_ID }}
          service_token_secret: ${{ secrets.CLOUDFLARED_SERVICE_TOKEN_SECRET }}
          commands: |
            cd /apps/vuetracker
            git fetch
            git pull --rebase
            export NVM_DIR=/usr/local/nvm
            source /usr/local/nvm/nvm.sh
            corepack enable pnpm
            pnpm i
            export PM2_HOME=/usr/local/share/pm2
            /usr/local/share/pnpm/pm2 restart vuetracker --silent